### ISSUE TITLE
License(s) not compatible with GPL?

### ISSUE THREAD

**Issue by virtualritz** [yuyttenhove/meshless_voro#3]
Your crate uses `rug` which is using `gmp-mpfr-sys` which uses GNU GMP which is under the LGPL. `rug` is therefore also under LGPL.

I opened a PR (#2) that contains support for the `dashu` crate which is under the same dual Apache-2.0/MIT license as this crate.
I also added `malachite` support as this is another, fast popular Rust-native bigint crate. But the latter is also under an LGPL variant.

**TLDR; `meshless_voro` can only be licensed as-is, if the `rug` (or `malachite`, in my PR) crates would be linked dynamically, at runtime. This is not possible without making a wrapper around each crate that sets `crate-type = ["dylib"]` in the resp. `Cargo.toml` and then using that instead. I would think you would not want to jump through these hoops.**

Options:

* Quadruple license the crate under Apache-2.0, MIT, LGPL-3.0-only (coming from `malachite`) or LGPL-3.0+ (coming from `rug`). I.e. choosing one of the latter two backends precludes some sort of GPL licensing of the code in this crate.
   I added a section to the README in my PR to make this clear.

* If you do not want to put the code in your crate under GPL when those dependencies are used, I think the only sensible option is to drop support for the `rug` and `malachite` backends.
  When running the test suite `rug` amd `dashi` are on par so this wouldn't necessarily mean a performance penalty.

[`cargo-deny`](https://github.com/EmbarkStudios/cargo-deny) can btw. help detecting/avoiding these scenarios beforehand.

**Comment by yuyttenhove** [comment]
Hi, thanks a lot for bringing this to my attention. 
I definitely should have paid more attention to the licensing when publishing by crate...

I have not done any performance tests yet, but if the performance is good, the `num-bigint` crate seems like a good alternative as well (often used, well maintained, compatible licences), as only arbitrary precision integers are needed anyway.
If the performance is acceptable, I am not opposed to dropping the `rug` backend, which would make things a bit simpler maybe.

Let's continue the discussion in the corresponding PR (#2)
